# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

networks:
  local:
    driver: bridge

services:
  KekikParty:
    container_name : KekikParty
    image          : KekikParty:local
    tty            : true
    restart        : always
    build          : .

    volumes:
      - .:/usr/src/KekikParty
    networks:
      - local
    ports:
      - 1221:3310
